### ISSUE TITLE
New version of Infomap no longer identifies planted structure in temporal network

### ISSUE THREAD

**Issue by LJeub** [mapequation/infomap#16]
Hi,

I was trying to update some numerical experiments and found that I was no longer able to identify the planted partition in my benchmark networks using newer versions of Infomap (I tested both `v0.19.13` and `v0.18.27`). An example of a network that exhibits the problem is included in [temporal_benchmark.zip](https://github.com/mapequation/infomap/files/1546119/temporal_benchmark.zip).

I'm running Infomap from the command line as follows:

    Infomap temporal_benchmark.net ./ --multiplex-relax-rate 0.1 --multiplex-relax-limit 1 -i multiplex --clu --expanded --seed 208588912 --out-name temporal_benchmark

(the actual value of `--seed` varies)

When using `v0.18.2`, the resulting partition closely resembles the planted partition (average NMI ~0.96 between identified and planted partition in each layer). 

When using `v0.19.13` or `v0.18.27`, the resulting partition barely has any resembles with the planted partition (average NMI ~0.1).

This particular network should not be a very hard benchmark, running Infomap separately on each layer results in an average NMI ~0.91.

**Comment by danieledler** [comment]
Thanks for the good feedback, we will look into this now!

**Comment by danieledler** [comment]
Sorry for the delay, for v0.18.2 with your seed I got 88 top modules, is that what you got too? In later versions it finds around five super modules above those, at least as best of multiple runs (-N 10). The --clu flag prints out just the top modules, so if you get similar output, it is a bit strange that the NMI is ~0.1 on the five cluster solution and ~0.96 on the 88 cluster solution, given that you have five planted clusters.

To dig into this further, it would be very helpful if you can share code or more details from the generation of the benchmark network and .clu file to the calculation of NMI so that we are able reproduce your result.

Thanks!
