### ISSUE TITLE
inner-parallelization option doesn't work

### ISSUE THREAD

**Issue by YankeeTsao** [mapequation/infomap#192]
I use the inner-parallelization option in local mode(linux), it doesn't work, please help~
```
im = Infomap('--two-level --markov-time 0.5 -FFF --inner-parallelization')
im.run()
partition = dict(im.get_modules(depth_level=-1))
```
when I add "--inner-parallelization", it gets even slower.

**Comment by danieledler** [comment]
Hi,

I recently did some tests with “—inner-parallellization” and discovered the same thing.

The reason is that Infomap since the first implementation of that feature has been optimised for a near-optimal solution with very low threshold values, and the better solution it finds the faster it goes. So for the inner-parallelization to be useful, we need to increase threshold values such as "--core-loop-codelength-threshold” to around 1e-2 instead of 1e-10.

That is not enough though, we need to work a bit more on the optimization of the inner parallelization.

If the reason for running it is to be able to handle very big networks, I would currently recommend other means, for example "--core-loop-codelength-threshold 1e-1 --tune-iteration-limit 1". The first parameter ends the inner loop quicker and the other skips fine and coarse tuning steps. With these parameters you will of course get a bit worse solution, but maybe in 30% of the time, so it's a trade-off you can explore.

I hope it solves the current issue for now, but if you really need the inner-parallelization to work, please re-open and describe your case in more detail.
