### ISSUE TITLE
Does infomap not work with points that are too long, such as bank card numbers of similar length?

### ISSUE THREAD

**Issue by zhangke-zhangke** [mapequation/infomap#355]
Building Infomap network from a NetworkX graph...
node : (320015954360525044901, 320015963360525029312)
type  : <class 'int'> <class 'int'>

error :
Traceback (most recent call last):
  File "D:/Gitlab/CommunityDetection/Infomap.py", line 225, in <module>
    a.printCom(graph)
  File "D:/Gitlab/CommunityDetection/Infomap.py", line 70, in printCom
    self.findCommunities(G)
  File "D:/Gitlab/CommunityDetection/Infomap.py", line 46, in findCommunities
    network.addLink(*e)
  File "D:\Anaconda3\envs\graph\lib\site-packages\infomap.py", line 2414, in addLink
    return _infomap.StateNetwork_addLink(self, *args)
TypeError: Wrong number or type of arguments for overloaded function 'StateNetwork_addLink'.
  Possible C/C++ prototypes are:
    infomap::StateNetwork::addLink(unsigned int,unsigned int,double)
    infomap::StateNetwork::addLink(unsigned int,unsigned int)
    infomap::StateNetwork::addLink(unsigned int,unsigned int,unsigned long)

**Comment by danieledler** [comment]
Hi. As you may see we use unsigned integers for node ids, which in C++ are 32 bits long covering the range 0 to 4294967295. This should be enough to uniquely identify all nodes for all practical purposes. If you have larger integers to identify nodes, such as bank card numbers, you have to map those to lower integers. In NetworkX you can simply run [convert_node_labels_to_integers](https://networkx.org/documentation/stable/reference/generated/networkx.relabel.convert_node_labels_to_integers.html) to do that.

If you want to include such long ids in Infomap, you have to convert them to strings and use as node names instead of ids. If you already have or convert the ids to strings in NetworkX and add the graph to Infomap with [add_networkx_graph](https://mapequation.github.io/infomap/python/infomap.html#infomap.Infomap.add_networkx_graph), it will automatically run the above function and store the string ids as node names.
