### ISSUE TITLE
Explanation for the ergodic node visit probability

### ISSUE THREAD

**Issue by MayaHanna** [mapequation/infomap#42]
I understood from your article that you use a "random walker" algorithm to calculate the  ergodic node visit probablity. I've tried using the pagerank (networkx implementaion) of a node as the visit probabilty, but when I compared my results to your example they were different. 
In your code, I noticed that you use something called "flow", I'm trying to understand what it is.
Could you please refer me to an explanation for this?

**Comment by danieledler** [comment]
Yes, flow is basically the visit rate or PageRank. For undirected networks they should match, for directed it will probably differ because by default Infomap use teleportation to links rather than nodes, which is the default for NetworkX. For more information on that, see http://www.mapequation.org/publications.html#Lambiotte-Rosvall-2012-Smart-teleportation

> Random teleportation is a necessary evil for ranking and clustering directed networks based on random walks. Teleportation enables ergodic solutions, but the solutions must necessarily depend on the exact implementation and parametrization of the teleportation. For example, in the commonly used PageRank algorithm, the teleportation rate must trade off a heavily biased solution with a uniform solution. Here we show that teleportation to links rather than nodes enables a much smoother trade-off and effectively more robust results.

If you use `--to-nodes`, do they match then?

**Comment by MayaHanna** [comment]
I've tried using the --to-nodes option and I'm still getting different results.

**Comment by danieledler** [comment]
Ok, can you share the relevant code and the network you use? It would make it easier for me to identify the issue.
