### ISSUE TITLE
Code length/map equation calculation

### ISSUE THREAD

**Issue by ranmrglt** [mapequation/infomap#43]
I'm trying to implement the map equation calculation as it appears in [The Map Equation article](http://www.mapequation.org/assets/publications/EurPhysJ2010Rosvall.pdf) 
and I'm not getting similar results to your code.
Even when I ignore the differences in PageRank/Flow calculation and use your results as a mock, the rest of the map equation calculation itself returns a different result.
 
I've tried reading your C++ implementation and I cannot see any connection to either two forms of the map equation ((1) or (4)). From my understanding the function calcCodelengthOnModuleOfModules is the calculation of map equation on modules.
Your comment in that code segment says:

>    // Expanded format
>     // L = q * -log(q) - q * -log(T) + SUM( p * -log(p) - p * -log(T) ) = T * log(T) - q*log(q) - SUM( p*log(p) )

Again, this form of calculation is nowhere to be seen in the Map Equation article.
 
I believe this is the core difference between my implementation (from my understanding of the article) and yours.
 
Could you please explain the logic of your calculation?

**Comment by antoneri** [comment]
Please see [Mapping higher-order network flows in memory and multilayer networks with Infomap](https://www.mapequation.org/publications.html#Edler-Etal-2017-MappingHigherOrder)
section 3 (pp. 7-9).

Reopen the issue if you have any questions!

**Comment by danieledler** [comment]
Hi @ranmrglt,

Sorry for the late reply, I see that there is a bit of a gap between the definitions in the articles and our code, and I also see a small error in the comment for the normal format, so I will explain a bit more.

First, the function `calcCodelengthOnModuleOfModules` is for the hierarchical map equation, where you have modules of modules. In that case, the map equation doesn't encode flow within the module but only the enter flow, which differ from the encoding of modules of leaf nodes, defined in the method above, `calcCodelengthOnModuleOfLeafNodes`.

Otherwise the equation is the same, but for modules of modules, the sum of the enter flows is not known in advance as the sum of flow, which is why we use the expanded format to not have to loop twice.

In the map equation article, if we start from equation 1, we are dealing with the part after the summation:

<img src="https://render.githubusercontent.com/render/math?math=p_%7B%5Ccirclearrowright%7D%5Ei%20H%28%5Cmathcal%7BP%7D%5Ei%29%0A">

As expanded in equation 3, with the notation from the comments in the code, it corresponds to the compact format below, except here p is the enter flow instead of flow.

```
// H(x) = -xlog(x), T = q + SUM(p), q = exitFlow, p = enterFlow
// Normal format
// L = q * -log(q/T) + SUM(p * -log(p/T))
// Compact format
// L = T * ( H(q/T) + SUM( H(p/T) ) )
// Expanded format
// L = q * -log(q) - q * -log(T) + SUM( p * -log(p) - p * -log(T) ) 
// = T * log(T) - q*log(q) - SUM( p*log(p) )
// = -H(T) + H(q) + SUM(H(p))
```
In the normal format, H has been expanded and T cancelled. In the current code the first p ended up in the wrong side of the sum though.

By using the fact that `log(a/b) = log(a) - log(b)` we get first form of the expanded format, simplified to the three terms in the end.

Hope this helps, and please comment if something is still unclear!
